apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-hopper-role
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - create
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - get
  - list
