env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - airbnb/hooks
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project:
    - ./tsconfig.json
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .json
        - .ts
        - .tsx
  react/jsx-props-no-spredaing:
    exceptions:
      - TextField
plugins:
  - react
  - '@typescript-eslint'
rules:
  'react/react-in-jsx-scope': 'off'
  'react/prop-types': 'off'
  'import/extensions':
    - error
    - {js: 'never', jsx: 'never', ts: 'never', tsx: 'never'}
  'react/jsx-filename-extension':
    - error
    - {extensions: ['.jsx', '.tsx']}
  'react/jsx-props-no-spreading': 'off'
  'import/prefer-default-export': 'off'
