name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - src/**

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy, rustfmt
            override: true

      - name: Build
        run: cargo test

      - name: Test
        run: cargo test

      - name: Format
        run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
